### ISSUE TITLE
Not working in gnome-shell 3.34

### ISSUE THREAD

**Issue by hashstat** [AndresCidoncha/audio-switcher#12]
It looks like the latest gnome-shell, version 3.34, breaks this extension.

I am using Arch Linux.

**Comment by AndresCidoncha** [comment]
Do you have any log? It could be useful for debugging.

**Comment by hashstat** [comment]
From systemd journal when I enable the extension:
```
JS ERROR: Extension audio-switcher@AndresCidoncha: TypeError: this._updateDefaultSource is not a function
AudioInputSubMenu@/home/brandon/.local/share/gnome-shell/extensions/audio-switcher@AndresCidoncha/extension.js:78:3
enable@/home/brandon/.local/share/gnome-shell/extensions/audio-switcher@AndresCidoncha/extension.js:141:22
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:131:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:99:13
```

**Comment by ilvidel** [comment]
Same error in Debian bullseye
