### PR TITLE
Fix extension error on Gnome 3.34

### LINKED ISSUE #12: Not working in gnome-shell 3.34
It looks like the latest gnome-shell, version 3.34, breaks this extension.

I am using Arch Linux.

### PR DESCRIPTION
**Pull request by christoph-heiss**
Fixes #12 

Hi,

I'm running Arch, which already has Gnome 3.34(.1).
Basically, my previous fix for Gnome 3.32 was broken by this update, due to some internal magic sourcery.

```
JS ERROR: Extension audio-switcher@AndresCidoncha: TypeError: this._updateDefaultSource is not a function
```

[This](https://stackoverflow.com/a/57549355) explains the issue pretty good - easy fix via `GObject.registerClass(..)`.

Also while at it, I replaced all remaining usages of the `Lang` module, which seems to be deprecated as a whole apparently.

I only tested this on Gnome 3.34 - I cannot say if it also works with Gnome 3.32, but I suppose it does.

### CODE REVIEW

**Comment by hackel** [comment]
This PR allows the extension to load, however it doesn't show any audio devices.

Edit: Nevermind, likely a case of https://github.com/anduchs/audio-output-switcher/issues/5.

**Comment by AndresCidoncha** [comment]
Thanks for your contribution!
